version: '3.8'
volumes:
  todos-db:
    driver: local

services:
  postgres:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
    container_name: postgres
    image: postgres:17
    hostname: postgres
    volumes:
      - todos-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: todos
      POSTGRES_PASSWORD: todos
      POSTGRES_DB: todos
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres